from configs.config import Config


class DevelopmentConfig(Config):
    DEBUG = True
    DB_NAME = "dynamodb"
    AWS_ACCESS_KEY_ID = "ASIAUDAIRGYVZUAJMJGF"
    AWS_SECRET_ACCESS_KEY = "NvbIeleOtJSQW84O0G8XQOMLkEGIXZ0VKjJG18uz"
    AWS_SESSION_TOKEN = "FwoGZXIvYXdzEAYaDPnkhGSc06IjIbeCmCLAAatxaTIiNcNEJTdqOEEUmRr9QWeYLJtVvy4G4K1Rvqw84XiZ2ANlMsjjEaVowl6rb7eT479KU+vkL/xFBQHPKUqGBJyRi1RVYniMArfvYOeO6aBiGQABAzYOoHMYQwMx8KbQSE83a7o1x3sXb67TI/4ZzQMLDTwXa53Umv7wbfL6ZjslS6hu5pqPUm5q2IPSvVDBhzg0xSTq45JAgBhLFFRDQH0jXSjsX6GByM3wuB7xeLPf5tZz1B4tlYR0DZgjUCiltcCRBjItOeVJPlfvs6JQqy5VfslsMYinXHMWZgeIcL8DWkDpYM7n17GUClcjjFig5QgB"
    AWS_REGION = "us-east-1"
    AWS_SESSION = ""
